
services:
  dns:
    image: smartdns-edge
    build:
      context: .
      dockerfile: docker/Dockerfile  # 指向我们优化的 Dockerfile
    ports:
      - "53:53"
      - "53:53/udp"
      - "8000:8000"                  # 🌟 暴露内置的 WebAPI & 网页管理控制台端口
    volumes:
      - ./smartdns.conf:/etc/smartdns/smartdns.conf # 🌟 统一挂载路径到标准目录
    restart: always