# .github/workflows/version.yml
name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: '选择升级版本类型 (Patch:修Bug, Minor:新功能, Major:大版本重构)'
        required: true
        type: choice
        options: [patch, minor, major, rc, beta, alpha]
        default: 'patch'

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      version: ${{env.version}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false 
        fetch-depth: 0 

    - name: Setup
      uses: ./.github/actions/setup

    # 自动修改项目版本号
    - name: Bump version ${{ github.event.inputs.bump }}
      run: |
        just bump ${{ github.event.inputs.bump }}
        echo "version=v$(just version)" >> "$GITHUB_ENV"
        
    # 自动提交修改并打上 Git Tag
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "🔖 Bump version to $version"
        git tag -a $version -m ""

    # 推送带 Tag 的代码到 GitHub
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true

  # 呼叫 build.yml 进行全平台交叉编译并发布到 Releases
  build:
    needs: [ "bump" ]
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.bump.outputs.version }}
      prerelease: ${{ !contains('major, minor, patch', inputs.bump) }}